// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy_policy from "./routes/privacy-policy.tsx";
import * as $templates_airflow_aws from "./routes/templates/airflow/aws.tsx";
import * as $templates_airflow_azure from "./routes/templates/airflow/azure.tsx";
import * as $templates_airflow_dev from "./routes/templates/airflow/dev.tsx";
import * as $templates_airflow_gcp from "./routes/templates/airflow/gcp.tsx";
import * as $templates_airflow_index from "./routes/templates/airflow/index.tsx";
import * as $templates_hop_aws from "./routes/templates/hop/aws.tsx";
import * as $templates_hop_azure from "./routes/templates/hop/azure.tsx";
import * as $templates_hop_dev from "./routes/templates/hop/dev.tsx";
import * as $templates_hop_gcp from "./routes/templates/hop/gcp.tsx";
import * as $templates_hop_index from "./routes/templates/hop/index.tsx";
import * as $templates_index from "./routes/templates/index.tsx";
import * as $templates_kafka_aws from "./routes/templates/kafka/aws.tsx";
import * as $templates_kafka_azure from "./routes/templates/kafka/azure.tsx";
import * as $templates_kafka_dev from "./routes/templates/kafka/dev.tsx";
import * as $templates_kafka_gcp from "./routes/templates/kafka/gcp.tsx";
import * as $templates_kafka_index from "./routes/templates/kafka/index.tsx";
import * as $templates_mongodb_aws from "./routes/templates/mongodb/aws.tsx";
import * as $templates_mongodb_azure from "./routes/templates/mongodb/azure.tsx";
import * as $templates_mongodb_dev from "./routes/templates/mongodb/dev.tsx";
import * as $templates_mongodb_gcp from "./routes/templates/mongodb/gcp.tsx";
import * as $templates_mongodb_index from "./routes/templates/mongodb/index.tsx";
import * as $templates_mssqlserver_aws from "./routes/templates/mssqlserver/aws.tsx";
import * as $templates_mssqlserver_azure from "./routes/templates/mssqlserver/azure.tsx";
import * as $templates_mssqlserver_dev from "./routes/templates/mssqlserver/dev.tsx";
import * as $templates_mssqlserver_gcp from "./routes/templates/mssqlserver/gcp.tsx";
import * as $templates_mssqlserver_index from "./routes/templates/mssqlserver/index.tsx";
import * as $templates_mysql_aws from "./routes/templates/mysql/aws.tsx";
import * as $templates_mysql_azure from "./routes/templates/mysql/azure.tsx";
import * as $templates_mysql_dev from "./routes/templates/mysql/dev.tsx";
import * as $templates_mysql_gcp from "./routes/templates/mysql/gcp.tsx";
import * as $templates_mysql_index from "./routes/templates/mysql/index.tsx";
import * as $templates_neo4j_aws from "./routes/templates/neo4j/aws.tsx";
import * as $templates_neo4j_azure from "./routes/templates/neo4j/azure.tsx";
import * as $templates_neo4j_dev from "./routes/templates/neo4j/dev.tsx";
import * as $templates_neo4j_gcp from "./routes/templates/neo4j/gcp.tsx";
import * as $templates_neo4j_index from "./routes/templates/neo4j/index.tsx";
import * as $templates_postgres_aws from "./routes/templates/postgres/aws.tsx";
import * as $templates_postgres_azure from "./routes/templates/postgres/azure.tsx";
import * as $templates_postgres_dev from "./routes/templates/postgres/dev.tsx";
import * as $templates_postgres_gcp from "./routes/templates/postgres/gcp.tsx";
import * as $templates_postgres_index from "./routes/templates/postgres/index.tsx";
import * as $terms_of_use from "./routes/terms-of-use.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LogoTicker from "./islands/LogoTicker.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/privacy-policy.tsx": $privacy_policy,
    "./routes/templates/airflow/aws.tsx": $templates_airflow_aws,
    "./routes/templates/airflow/azure.tsx": $templates_airflow_azure,
    "./routes/templates/airflow/dev.tsx": $templates_airflow_dev,
    "./routes/templates/airflow/gcp.tsx": $templates_airflow_gcp,
    "./routes/templates/airflow/index.tsx": $templates_airflow_index,
    "./routes/templates/hop/aws.tsx": $templates_hop_aws,
    "./routes/templates/hop/azure.tsx": $templates_hop_azure,
    "./routes/templates/hop/dev.tsx": $templates_hop_dev,
    "./routes/templates/hop/gcp.tsx": $templates_hop_gcp,
    "./routes/templates/hop/index.tsx": $templates_hop_index,
    "./routes/templates/index.tsx": $templates_index,
    "./routes/templates/kafka/aws.tsx": $templates_kafka_aws,
    "./routes/templates/kafka/azure.tsx": $templates_kafka_azure,
    "./routes/templates/kafka/dev.tsx": $templates_kafka_dev,
    "./routes/templates/kafka/gcp.tsx": $templates_kafka_gcp,
    "./routes/templates/kafka/index.tsx": $templates_kafka_index,
    "./routes/templates/mongodb/aws.tsx": $templates_mongodb_aws,
    "./routes/templates/mongodb/azure.tsx": $templates_mongodb_azure,
    "./routes/templates/mongodb/dev.tsx": $templates_mongodb_dev,
    "./routes/templates/mongodb/gcp.tsx": $templates_mongodb_gcp,
    "./routes/templates/mongodb/index.tsx": $templates_mongodb_index,
    "./routes/templates/mssqlserver/aws.tsx": $templates_mssqlserver_aws,
    "./routes/templates/mssqlserver/azure.tsx": $templates_mssqlserver_azure,
    "./routes/templates/mssqlserver/dev.tsx": $templates_mssqlserver_dev,
    "./routes/templates/mssqlserver/gcp.tsx": $templates_mssqlserver_gcp,
    "./routes/templates/mssqlserver/index.tsx": $templates_mssqlserver_index,
    "./routes/templates/mysql/aws.tsx": $templates_mysql_aws,
    "./routes/templates/mysql/azure.tsx": $templates_mysql_azure,
    "./routes/templates/mysql/dev.tsx": $templates_mysql_dev,
    "./routes/templates/mysql/gcp.tsx": $templates_mysql_gcp,
    "./routes/templates/mysql/index.tsx": $templates_mysql_index,
    "./routes/templates/neo4j/aws.tsx": $templates_neo4j_aws,
    "./routes/templates/neo4j/azure.tsx": $templates_neo4j_azure,
    "./routes/templates/neo4j/dev.tsx": $templates_neo4j_dev,
    "./routes/templates/neo4j/gcp.tsx": $templates_neo4j_gcp,
    "./routes/templates/neo4j/index.tsx": $templates_neo4j_index,
    "./routes/templates/postgres/aws.tsx": $templates_postgres_aws,
    "./routes/templates/postgres/azure.tsx": $templates_postgres_azure,
    "./routes/templates/postgres/dev.tsx": $templates_postgres_dev,
    "./routes/templates/postgres/gcp.tsx": $templates_postgres_gcp,
    "./routes/templates/postgres/index.tsx": $templates_postgres_index,
    "./routes/terms-of-use.tsx": $terms_of_use,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LogoTicker.tsx": $LogoTicker,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
