// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $templates_airflow_aws from "./routes/templates/airflow/aws.tsx";
import * as $templates_airflow_azure from "./routes/templates/airflow/azure.tsx";
import * as $templates_airflow_dev from "./routes/templates/airflow/dev.tsx";
import * as $templates_airflow_gcp from "./routes/templates/airflow/gcp.tsx";
import * as $templates_airflow_index from "./routes/templates/airflow/index.tsx";
import * as $templates_index from "./routes/templates/index.tsx";
import * as $templates_neo4j_aws from "./routes/templates/neo4j/aws.tsx";
import * as $templates_neo4j_azure from "./routes/templates/neo4j/azure.tsx";
import * as $templates_neo4j_dev from "./routes/templates/neo4j/dev.tsx";
import * as $templates_neo4j_gcp from "./routes/templates/neo4j/gcp.tsx";
import * as $templates_neo4j_index from "./routes/templates/neo4j/index.tsx";
import * as $templates_postgres_aws from "./routes/templates/postgres/aws.tsx";
import * as $templates_postgres_azure from "./routes/templates/postgres/azure.tsx";
import * as $templates_postgres_dev from "./routes/templates/postgres/dev.tsx";
import * as $templates_postgres_gcp from "./routes/templates/postgres/gcp.tsx";
import * as $templates_postgres_index from "./routes/templates/postgres/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LogoTicker from "./islands/LogoTicker.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/templates/airflow/aws.tsx": $templates_airflow_aws,
    "./routes/templates/airflow/azure.tsx": $templates_airflow_azure,
    "./routes/templates/airflow/dev.tsx": $templates_airflow_dev,
    "./routes/templates/airflow/gcp.tsx": $templates_airflow_gcp,
    "./routes/templates/airflow/index.tsx": $templates_airflow_index,
    "./routes/templates/index.tsx": $templates_index,
    "./routes/templates/neo4j/aws.tsx": $templates_neo4j_aws,
    "./routes/templates/neo4j/azure.tsx": $templates_neo4j_azure,
    "./routes/templates/neo4j/dev.tsx": $templates_neo4j_dev,
    "./routes/templates/neo4j/gcp.tsx": $templates_neo4j_gcp,
    "./routes/templates/neo4j/index.tsx": $templates_neo4j_index,
    "./routes/templates/postgres/aws.tsx": $templates_postgres_aws,
    "./routes/templates/postgres/azure.tsx": $templates_postgres_azure,
    "./routes/templates/postgres/dev.tsx": $templates_postgres_dev,
    "./routes/templates/postgres/gcp.tsx": $templates_postgres_gcp,
    "./routes/templates/postgres/index.tsx": $templates_postgres_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LogoTicker.tsx": $LogoTicker,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
